# Generated by Django 3.0.6 on 2020-05-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temphum', '0002_cultivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultivo',
            old_name='latidud',
            new_name='latitud',
        ),
    ]
